### ISSUE TITLE
Getting many 'TXStatus.MAC_NO_ACK' and 'TXStatus.MAC_CHANNEL_ACCESS_FAILURE' errors

### ISSUE THREAD

**Issue by basnijholt** [zigpy/zigpy-deconz#140]
Last weekend I moved over >50 devices from deCONZ to ZHA. Not because I was experiencing issues with deCONZ but because I liked the Python solution (which will allow me to contribute back.)

Unfortunately, it's not working very well for me now. Often, when changing the state of a light
* HA will report that the state _is_ changed while the light _didn't_ change
* HA will report that the state _isn't_ changed while the light _did_ change

From my 100 MB log I have identified 3 types of errors.
1. `TXStatus.MAC_NO_ACK` (1713 occurrences in ≈20 hours)
```
2020-10-27 20:48:55 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 186: e9
2020-10-27 20:48:55 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0xba 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0x448b endpoint=11>, status: 0xe9
2020-10-27 20:48:55 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Error while sending 186 req id frame: TXStatus.MAC_NO_ACK
2020-10-27 20:48:55 DEBUG (MainThread) [zigpy.device] [0x448b] Delivery error for seq # 0xb9, on endpoint id 11 cluster 0x0008: message send failure
```
2. `TXStatus.MAC_CHANNEL_ACCESS_FAILURE` (2055 occurrences in ≈20 hours)
```
2020-10-27 20:48:49 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x80 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0x1d20 endpoint=11>, status: 0xe1
2020-10-27 20:48:49 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Error while sending 128 req id frame: TXStatus.MAC_CHANNEL_ACCESS_FAILURE
2020-10-27 20:48:49 DEBUG (MainThread) [zigpy.device] [0x1d20] Delivery error for seq # 0x7f, on endpoint id 11 cluster 0x0300: message send failure
```

3. (maybe not `zigpy-deconz` related but `zigpy`) `{'move_to_level_with_on_off': TimeoutError()}`, `{'move_to_color_temp': TimeoutError()}`, `{'move_to_color': TimeoutError()}`, `{'on_off': TimeoutError()}` (1478 occurrences in ≈20 hours) like:
```
2020-10-27 20:52:15 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x06DB:11:0x0300]: executed 'move_to_color' command with args: '(39255, 25034, 150.0)' kwargs: '{}' result: [7, <Status.SUCCESS: 0>]
2020-10-27 20:52:15 DEBUG (MainThread) [homeassistant.components.zha.entity] light.tv_led: turned on: {'move_to_level_with_on_off': [4, <Status.SUCCESS: 0>], 'on_off': [1, <Status.SUCCESS: 0>], 'move_to_color': [7, <Status.SUCCESS: 0>]}
2020-10-27 20:52:18 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x1D20:11:0x0008]: command failed: 'move_to_level_with_on_off' args: '(198, 10.0)' kwargs '{}' exception: ''
2020-10-27 20:52:18 DEBUG (MainThread) [homeassistant.components.zha.entity] light.sphere_2: turned on: {'move_to_level_with_on_off': TimeoutError()}
```
but that might be a different problem and might be solved by retrying (https://github.com/zigpy/zigpy/pull/527).

I am using HA 0.117.0, Hue light lights (most recent firmware), and a ConBee II stick (I tried the three most recent firmware versions `deCONZ_ConBeeII_0x26650700.bin.GCF`, `deCONZ_ConBeeII_0x26660700.bin.GCF`, `deCONZ_ConBeeII_0x26580700.bin.GCF`).

I would really appreciate some suggestions on how to debug this or some insight into why these issues might occur.

I have uploaded the first 10.000 lines of my log here http://files.nijho.lt/home-assistant_truncated.log

**Comment by basnijholt** [comment]
I found that https://github.com/home-assistant/core/issues/39236 reports a very similar issue.

**Comment by basnijholt** [comment]
When downgrading to the fourth last firmware (`deCONZ_ConBeeII_0x26570700.bin.GCF`)
I see a many instances of a different error (`TXStatus.NWK_ROUTE_DISCOVERY_FAILED`):
```
2020-10-29 10:06:24 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x405D:11:0x0008]: initializing channel: from_cache: False
2020-10-29 10:06:24 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Sending Zigbee request with tsn 137 under 138 request id, data: b'0089000000'
2020-10-29 10:06:24 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_confirm (0,)
2020-10-29 10:06:24 DEBUG (MainThread) [zigpy_deconz.api] APS data confirm response for request with id 136: d0
2020-10-29 10:06:24 DEBUG (MainThread) [zigpy_deconz.api] Request id: 0x88 'aps_data_confirm' for <DeconzAddressEndpoint address_mode=ADDRESS_MODE.NWK address=0x405d endpoint=11>, status: 0xd0
2020-10-29 10:06:24 DEBUG (MainThread) [zigpy_deconz.zigbee.application] Error while sending 136 req id frame: TXStatus.NWK_ROUTE_DISCOVERY_FAILED
2020-10-29 10:06:24 DEBUG (MainThread) [zigpy.device] [0x405d] Delivery error for seq # 0x87, on endpoint id 11 cluster 0x0300: message send failure
2020-10-29 10:06:24 DEBUG (MainThread) [homeassistant.components.zha.core.channels.base] [0x405D:11:0x0300]: failed to get attributes '['color_temperature', 'current_x', 'current_y']' on 'light_color' cluster: [0x405d:11:0x0300]: Message send failure
2020-10-29 10:06:24 DEBUG (MainThread) [zigpy_deconz.api] Command Command.aps_data_request (20, 138, 0, <DeconzAddressEndpoint address_mode=2 address=0x405D endpoint=11>, 260, 8, 1, b'\x00\x89\x00\x00\x00', 2, 0)
```

**Comment by TheJulianJES** [comment]
I also had a similar issue with a ConBee II (with USB Extension) and ZHA. Just ended up switching to an Elelabs ELU013. The issue, for me, didn’t seem to happen with deCONZ on a very similar setup.

**Comment by Adminiuga** [comment]
TXStatus.MAC_CHANNEL_ACCESS_FAILURE (2055 occurrences in ≈20 hours) is a sign of rf interference. 
If you get those, anything else will be working the way you see it right now.

Make sure the stick is not in usb 3 port
Make sure there are no usb3 devices near by
Use usb extension
Change to a different channel - 15, 20 or 25 ( would need deCONZ for that)
Move wifi in 2.4ghz to different channel and make sure it's not using 40mHz channel bonding

**Comment by basnijholt** [comment]
I have already moved my WiFi to a channel away from the frequency that the Conbee II uses and my neighbors aren't using any nearby channels either. 

I also use a USB extension cord on my NUC, however, I do not have a USB 2 port, but since I have successfully used deCONZ for a year using the same port, I can hardly believe this is the issue.

I find it hard to believe that this is just a hardware issue,  precisely because I have had no issues with deCONZ.

I never changed my Zigbee channel in deCONZ, perhaps ZHA uses a different default channel and maybe that explains it?

**Comment by Adminiuga** [comment]
Zha does not change the channel, if the network is already formed. ~~What channel is it running on currently?~~ You are on channel 15.
What channel is your WiFi network?
neighbours WiFi? 
What HA version?

**Comment by basnijholt** [comment]
> What channel is your WiFi network?

13

> neighbours WiFi?

What HA version?

**Comment by basnijholt** [comment]
> What channel is your WiFi network?

channel 13

> neighbours WiFi?

channel 11

> What HA version?

0.117.0


But do you agree with my intuition? That if it worked perfectly fine with this configuration on deCONZ, it shouldn't give issues with ZHA?

**Comment by Adminiuga** [comment]
I see your point however I also see the logs and in 10 min from the start you had:
~21 - MAC_CHANNEL_ACCESS failures
~31 - MAC_NO_ACK

Which means at least 1 out 15 requests are failing. (per 10 min log the success rate is ~92.4%)
From my perspective MAC_CHANNEL_ACCESS is particularly bad, because it means ConBee wanted to send data multiple times, but couldn't because every time the channel was busy. This is from ConBee, but it also means that any other device potentially experiencing this issue, so even if it sent out successfully, you still might not get the reply. i.e. if ConBee is having issues talking to the devices because of interference, then it is very likely devices are having issues talking to ConBee

You also have only HUE lights, which do not report state. Unlike any other implementations, ZHA relies heavily on lights/devices pushing updates to the coordinator, but HUE does not do that. ZHA polls those once every 15min IIRC but: per light that is at least three requests per poll (On/off, Color, level clusters) and with failure rate of 1 per 15, that means that at least for 1 out of 3 lights the poll request is going to be incomplete. 

I know deCONZ does retry specfic request, but I don't know all the details. But with so many requests failing I know ZHA cannot function correctly. 
What channel deCONZ was running on? Do you have any other HUBs on the same channel? Bluetooth?

**Comment by TheJulianJES** [comment]
Just some information: The newer Philips Hue bulbs (with the ZHA profile reported instead of the ZLL profile/the Zigbee 3.0 bulbs with the QR-Code on the package) do report state (which is also kind of annoying because the brightness slider and the default 1s transition but eh). (+ currently only the brightness and on/off state - not color - is parsed/display in HASS).

The Hue bulbs should all have a higher poll interval though:
https://github.com/home-assistant/core/blob/dev/homeassistant/components/zha/light.py#L486-L494
(That doesn't seem to have worked in my experience though, but perhaps this could overload a network?)
(I guess this isn't the case here though.)

**Comment by Adminiuga** [comment]
ah ok, yes HUE lights are being polled by ZHA randomly between 3-5 min each. 
Can you post a log of about 30-60min about 1 hour after HA restart? Right after the restart, HA polls all the lights and there's a traffic spike. I really interested to see the success rate of request after that spike

**Comment by basnijholt** [comment]
It doesn't get much better, unfortunately, here is my full ~116MB log http://files.nijho.lt/home-assistant.log

**Comment by Hedda** [comment]
Might not hurt to try to latest ConBee/RaspBee firmware.

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually

> TXStatus.MAC_CHANNEL_ACCESS_FAILURE (2055 occurrences in ≈20 hours) is **a sign of rf interference**.

> I also had a similar issue with a ConBee II (with USB Extension) and ZHA. Just ended up switching to an Elelabs ELU013. The issue, for me, didn’t seem to happen with deCONZ on a very similar setup.

While it might not help in this case, here is a copy of my tips on improving Zigbee network range and reducing RF interferance:

### Improving Zigbee network range

One of the more commonly asked questions about using Zigbee with Home Assistant are regarding to improving or extending signal reception/transmission or resolving problems with poor link quality, thus here are gathered a few possible options to resolve most problems related to range extension. 

The fact is that bad signal reception can be due to many different things and experienced Zigbee users in the community will normally advise that there are a few simple fundamental things that you should really attemt to do first in order to better optimize your Zigbee devices equipment which can resolve many basic problems related to signal strength or interferance issues. Note that there are always exceptions, however, if possible to try follow at least some of these general recommendations before you take more advanced steps like reporting issues to developers and submitting debug logs.

Just following these simple tips below should help improve signal strength and reduce signal interference which can normally many problems with a Zigbee network.

1. Add more Zigbee routers between the far away devices and the next nearest router, distributing more Zigbee routers around areas with poorer reception. Zigbee network topology uses a "mesh network" design which means that each device that acts as a Zigbee router will extend the range of your Zigbee network. While there are exceptions, as a rule of thumb, almost all permanently powered devices will serve as a router. This is a part of Zigbee design concept, simple add more powered permanently Zigbee devices to get better coverage, (there are purpose-specific Zigbee routers which you can [find by doing a community search for "Zigbee signal repeater" or "Zigbee range extender"](https://community.home-assistant.io/t/advice-on-zigbee-range-extending/175882/)). Devices that can not act as routers are known as "end devices" and you should know that some end device models from brands like Xiaomi/Aqara have issues connecting through routers.
2. Utilize a USB extension cable to move Zigbee coordinator adapter and place your Zigbee coordinator adapter in a sensible position, away from WiFi access-points/routers or other sources of 2.4GHz signals in a location that it is relatively free from strong signal interference. The best location will depend on your building's floorplan though normally you want to place it somewhere in the middle. Building materials are also very relative as example dense/thick concrete, bricks, masonry, etc. dampen will all wireless signals and therefore it is best to place your Zigbee coordinator adapter some distance from walls, ceilings and floors. You could also try different orientation of your Zigbee antenna (or your whole Zigbee coordinator adapter if it has an internal antenna). This is because the connection between the Zigbee coordinator radio and your other devices also depends on the way the antenna oriented in space. Note! A bad USB extension cable may lead to connection issues between the system and the Zigbee coordinator adapter, symptoms of this are disconnection messages.
3. Check your WiFi access-points/routers channels in use to see if your router/access point is overlapping the channel your Zigbee network is using. If so change the channel of the access-points/routers and lock it. It will normally be easier than changing the channel of your Zigbee network and then you will have to re-join/re-pair all of your Zigbee devices. A busy WiFi access-points/routers that are operating the same frequency range (overlapping channels) as your Zigbee coordinator will drown out the Zigbee traffic, and even more so if they are located close to each other. See [this article for WiFi and Zigbee channels coexistance](https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html) to avoid using overlapping frequency ranges.
4. Update the firmware on your Zigbee coordinator adapter and your Zigbee devices. Note that depending on your hardware the latest Zigbee coordinator firmware might not always be the one recommended by the community so it is advised to ask before upgrading.
5. If you Zigbee coordinator adapter a removable antenna with an SMA-connector then you have the option of buying a high-gain antenna as an upgrade. In addition, you also have the option to use an antenna extension-cable if needed (though for various reasons that is not a good alternative to only using a USB extension cable with your Zigbee coordinator adapter if possible). This should really only be needed if you are trying to cover a long distance, like to another building or very dense/thick walls, ceilings and floors.
6. Buy more powerful Zigbee radio hardware with better radio range, preferably with an external antenna. If you are not only experimenting but want a permanently stable and healthy Zigbee network with potentially many devices then you should consider upgrading to a more powerful Zigbee coordinator USB adapter. Generally, those with an external antenna will have better range, therefore you will also want to avoid buying an internal adapter unless it has an external antenna.

**Comment by majkrzak** [comment]
Any updates? I have issues with [blinking lightbulbs](https://community.home-assistant.io/t/zigbe-lightbulb-blinks-randomly/291676/2) and wonder if this may be releated?

**Comment by Adminiuga** [comment]
update to original issue https://github.com/zigpy/zigpy-deconz/issues/140#issuecomment-718782551
Your issue is unrelated.
