### ISSUE TITLE
Logger: zigpy_deconz.api Strange Warning pops up every few hours.

### ISSUE THREAD

**Issue by FCKotze** [zigpy/zigpy-deconz#148]
Hi there, 

I have a warning pop up in my logs every few hours, I don't know which device its relating to. None of my devices seems to be unresponsive or unavailable. I have a mixture of Zigbee devices with most of them being Philips Hue Bulbs and Motion Sensors.

The Error:

Logger: zigpy_deconz.api
Source: /usr/local/lib/python3.8/site-packages/zigpy_deconz/api.py:307
First occurred: 11:04:24 AM (3 occurrences)
Last logged: 12:26:02 PM

No response to 'Command.aps_data_indication' command with seq id '0xb1'
No response to 'Command.aps_data_indication' command with seq id '0x76'
No response to 'Command.aps_data_indication' command with seq id '0x6d'

Hope you'll be able to shed some light on what might be causing this issue. 

Thanks,

**Comment by Adminiuga** [comment]
Zigoy_deconz did not receive a response to some commands. If not happening constantly, then should be fine.

**Comment by abrinkman-gmail** [comment]
I’m having the same issue, but it is happening constantly.

Mostly when issuing multiple zigbee commands in succession. For instance when changing the state of a number of lights at once. When this happens the lights fail to report back their correct status (or take longer to report back) and sometimes the lights do not change state at all.

Could something swamp the mesh? All devices work fine otherwise.

**Comment by FCKotze** [comment]
Its now coming up every 10 minutes or so. Not sure why I still can't find anything not working.

**Comment by Kanishkaz** [comment]
I have the same issue. It seems to be more prominent since early this year.

My zigbee network has become unstable recently and frequently becomes unresponsive. The only error/ warning I keep seeing is this one. Restarting HA Core works sometimes, other times I need to do a Host reboot to resolve the issue. Interestingly, the network fails to recognise end device events (motion sensors, switches). Smart plugs/ lights that act as routers work.

Happy to provide any additional details.

```Logger: zigpy_deconz.api
Source: /usr/local/lib/python3.8/site-packages/zigpy_deconz/api.py:307
First occurred: 2:48:18 (12 occurrences)
Last logged: 8:38:26

No response to 'Command.aps_data_indication' command with seq id '0x52'
No response to 'Command.aps_data_indication' command with seq id '0x6a'
No response to 'Command.aps_data_indication' command with seq id '0xf3'
No response to 'Command.aps_data_indication' command with seq id '0x19'
No response to 'Command.aps_data_indication' command with seq id '0x60'

**Comment by Adminiuga** [comment]
ConBee is not responding **in time** to the commands.  For possible causes check https://github.com/home-assistant/core/issues/47982

Usually related to:
1. SD card going bad
2. Power supply going bad
3. Too much disk-io activity because of the large size >400MB of the `home-assistant_v2.db` file
4. Any `custom_component` doing IO or locking asyncio loop.

**Comment by Adminiuga** [comment]
nothin zigpy-deconz can do. Command is just dropped and next one is sent.

**Comment by mbo18** [comment]
Just to add some info: I'm using an Intel NUC so no SD card, no power issue. I'm not using custom components at all and I've setup filters to `recorder` so my db file is only 250MB :)
But I have a conbee2 (up to date) with Aqara/Xiaomi battery powered devices which, even with a lot of powered devices (plug and bulb), only pair to the conbee2... so LQI is bad and I think that's why we have these logs.

With HA 2021.4.0 and after we can now filter logs:
```yaml
logger:
  default: warning
  filters:
    zigpy_deconz.api:
      - "No response to 'Command.aps_data_indication'"
```
