### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by AlexKnowsIt** [zigpy/zigpy-deconz#152]
I am experiencing a really weird behaviour since the Release 2021.3.4 from deconz. I am seeing a similiar error as well with the cloudflare integration, both about the asyncio library. Would be nice if somebody can help me figure out if this is a deconz problem or a ha problem in general.

2021-03-15 05:48:40 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zigpy_deconz/api.py", line 305, in _command
    return await asyncio.wait_for(fut, timeout=COMMAND_TIMEOUT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zigpy_deconz/api.py", line 462, in _aps_data_indication
    r = await self._command(
  File "/usr/local/lib/python3.8/site-packages/zigpy_deconz/api.py", line 310, in _command
    self._awaiting.pop(seq)
KeyError: 133

**Comment by Adminiuga** [comment]
This means the stick has not responded in the allotted time to the command request. It did respond with a delay, when the command was already dropped and forgotten by zigpy_deconz. This could happen when ConBee self resets or because of some other issues, like failing SD card, failing power supply, running two HA instances, running both ZHA and deCONZ addons at the same time.

per se, there were no changes to zipgy_deconz code for a while now and definitely no in 2021.3.4 HA release

**Comment by MattWestb** [comment]
Is modem manager active in the OS (if running on  one normal  Linux) and trying hijacking the com port ??

**Comment by Adminiuga** [comment]
yeah, you are not giving any info about your setup, so may be other factors at play. But no zigpy-deconz changes in recent releases. But historically ConBees are known to be somewhat flaky after each upgrade. There's a burst of issues reported each update, even if there were no changes. I recommend after each update, physically unplug/plug the stick and restart HA instance, as HA container does not like/support hot-plugging the USB devices

**Comment by vinmar1** [comment]
I used to see those errors when I had radio interference with my Conbee a long time ago. Wrote up a page on it...
https://community.home-assistant.io/t/zigbee-conbee-and-wifi-interference/112945
I also dumped DeConz in favor of native ZigBee integration and experience virtually zero issues and it runs a lot faster but I know that can be a challenge depending on the number of devices you have.

**Comment by Adminiuga** [comment]
This is fixed (the crash part) in 0.12.0 release. The cause, as why it does not respond or does not respond in time differ, but usually related to:

- SD card going bad
- Power supply going bad
- Too much disk-io activity because of the large size >400MB of the home-assistant_v2.db file
- Any custom_component doing IO or locking asyncio loop
- ConBee self reseting?
